name = "Nesquate Server's Server Modpack"
author = "Nesquate"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31e9c8704aba0e14336bdaa01dbca8335b3dc4aa765b3f69a4d3d7b050601b2d"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = []
