name = "Nesquate Server's Server Modpack"
author = "Nesquate"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a805e0628e98f35d3b08e066120f0b41ac22bdb8c1fc8f1632981d7863472183"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = []
