name = "Nesquate Server's Server Modpack"
author = "Nesquate"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f317ae547ed2f4960e8c811fac19d799b6d18638a1424143a1439801aef01731"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.2"]
