name = "Server modpack for Nesquate's Minecraft Server"
author = "Nesquate"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b33cc1a884e71a9dd744c091c109aa09b70ac28506d2d710ca2f9eefdbe036f"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
