name = "Nesquate Server's Server Modpack"
author = "Nesquate"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "275b6c058e383e388e9c667ecdf261f4e875614009d25d15deb081fcc9ba6729"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = []
