name = "Server modpack for Nesquate's Minecraft Server"
author = "Nesquate"
version = "1.0.1-creative"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41c01a54cf913e5f0832916313d192d1da394c458087858419a48d44d337b694"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"
