name = "Nesquate Server's Server Modpack"
author = "Nesquate"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "692bf7f1ba8a711bbb055f08f474cb711310e7d19d0c04fe4c69336b615bf1e6"

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"

[options]
acceptable-game-versions = ["1.20.2"]
